// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKhafdgJj8obG93DsVx4AHpBIsyeL23As',
    appId: '1:411132249392:web:445897970b94646b98f4f5',
    messagingSenderId: '411132249392',
    projectId: 'msgs-a8cda',
    authDomain: 'msgs-a8cda.firebaseapp.com',
    storageBucket: 'msgs-a8cda.appspot.com',
    measurementId: 'G-7CSGD4023H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhmY0WYlZqfj5CG8s0aK9WRauHFjaKv5I',
    appId: '1:411132249392:android:7fb086c48a65c37298f4f5',
    messagingSenderId: '411132249392',
    projectId: 'msgs-a8cda',
    storageBucket: 'msgs-a8cda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaclQ7_e9WxhL2aoP7rR0MDGbP_ZQCiuw',
    appId: '1:411132249392:ios:d6083ec724e3cbbd98f4f5',
    messagingSenderId: '411132249392',
    projectId: 'msgs-a8cda',
    storageBucket: 'msgs-a8cda.appspot.com',
    iosClientId: '411132249392-5utk6sd7s37r7411qoadfqbndj08jgbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.msg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaclQ7_e9WxhL2aoP7rR0MDGbP_ZQCiuw',
    appId: '1:411132249392:ios:d6083ec724e3cbbd98f4f5',
    messagingSenderId: '411132249392',
    projectId: 'msgs-a8cda',
    storageBucket: 'msgs-a8cda.appspot.com',
    iosClientId: '411132249392-5utk6sd7s37r7411qoadfqbndj08jgbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.msg',
  );
}
